version: '3.8'

services:
  mysqldata:
    image:
      mysql

    ports:
      - "3306:3306"
    environment:
      {
        MYSQL_ROOT_PASSWORD=1234,
        MYSQL_DATABASE=blog_api
      }
networks:
    {appconnect}

